Chapter 02. Qubit: The building blocks


In [ ]:
def qrng(device : QuantumDevice) -> bool:
    with device.using_qubit() as q:
        q.h()
        return q.measure()

Listing 2.2. Using python to print out a truth table for NAND

In [2]:
from itertools import product
for inputs in product([False, True], repeat=2):
    output = not (inputs[0] and inputs[1])
    print(f"{inputs[0]}\t{inputs[1]}\t=>\t{output}")

False	False	=>	True
False	True	=>	True
True	False	=>	True
True	True	=>	False


In [3]:
import numpy as np
directions_in_meters = np.array([[30],[50]])
direction_in_feet = 3.28*directions_in_meters
direction_in_feet

array([[ 98.4],
       [164. ]])

Listing 2.4. Using NumPy to help compute f(np.array([[2], [3]])) 


In [4]:
horizontal = np.array([[1],[0]])
vertical = np.array([[0],[1]])
vec = 2 * horizontal + 3* vertical
vec

array([[2],
       [3]])

In [6]:
f_horizontal = np.array([[1],[1]])
f_vertical = np.array([[1],[-1]])
2*f_horizontal+3*f_vertical

array([[ 5],
       [-1]])

Listing 2.5. Stacking the vectors for swapping East/North conventions on a map 


In [7]:
swap_north_east = np.array([[0, 1], [1, 0]]) 
swap_north_east

array([[0, 1],
       [1, 0]])

Listing 2.6. Matrix multiplication with the @ operator

In [ ]:
# In NumpPy, matrix multiplication is represented by the @ operator
M = np.array([ [1, 1],  [1, -1] ], dtype=complex) 
M @ np.array([[2], [3]], dtype=complex) 

array([[ 5.+0.j],
       [-1.+0.j]])

Listing 2.7. Timing NumPy evaluation for matrix multiplication 


In [ ]:
def matmul(A, B):
    n_rows_A = len(A)
    n_cols_A = len(A[0])
    n_rows_B = len(B)
    n_cols_B = len(B[0])
    assert n_cols_A == n_rows_B 
    '''The inner dimensions of both matrices need to agree in order for matrix multiplication to make sense. Thinking of each matrix as representing a linear function, the first index (the number of rows) tells us how large each output is, while the second index (the number of columns) tells us how large each input is. Thus we need the outputs from the first function to be applied (the one on the right) to be of the same size as the inputs to the second function. This line checks that condition. '''
    return[
        [
            sum(
                A[idx_row][idx_inner]*B[idx_inner][idx_col]
                for idx_inner in range(n_cols_A)
            )
            for idx_col in range(n_cols_B)
        ]
        for idx_row in range(n_rows_A)
    ]
import numpy as np
X = np.array([[0+0j, 1+0j], [1+0j, 0+0j]])
Z = np.array([[1+0j, 0+0j], [0+0j, -1+0j]])
matmul(X,Z)


[[np.complex128(0j), np.complex128(-1+0j)],
 [np.complex128(1+0j), np.complex128(0j)]]

In [15]:
X @ Z

array([[ 0.+0.j, -1.+0.j],
       [ 1.+0.j,  0.+0.j]])

In [11]:
%timeit matmul(X,Z)

4.54 μs ± 175 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [12]:
%timeit X @ Z

901 ns ± 11.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
