Chapter 02. Qubit: The building blocks


In [ ]:
def qrng(device : QuantumDevice) -> bool:
    with device.using_qubit() as q:
        q.h()
        return q.measure()

Listing 2.2. Using python to print out a truth table for NAND

In [2]:
from itertools import product
for inputs in product([False, True], repeat=2):
    output = not (inputs[0] and inputs[1])
    print(f"{inputs[0]}\t{inputs[1]}\t=>\t{output}")

False	False	=>	True
False	True	=>	True
True	False	=>	True
True	True	=>	False


In [3]:
import numpy as np
directions_in_meters = np.array([[30],[50]])
direction_in_feet = 3.28*directions_in_meters
direction_in_feet

array([[ 98.4],
       [164. ]])

Listing 2.4. Using NumPy to help compute f(np.array([[2], [3]])) 


In [4]:
horizontal = np.array([[1],[0]])
vertical = np.array([[0],[1]])
vec = 2 * horizontal + 3* vertical
vec

array([[2],
       [3]])

In [6]:
f_horizontal = np.array([[1],[1]])
f_vertical = np.array([[1],[-1]])
2*f_horizontal+3*f_vertical

array([[ 5],
       [-1]])

Listing 2.5. Stacking the vectors for swapping East/North conventions on a map 


In [7]:
swap_north_east = np.array([[0, 1], [1, 0]]) 
swap_north_east

array([[0, 1],
       [1, 0]])

Listing 2.6. Matrix multiplication with the @ operator

In [ ]:
# In NumpPy, matrix multiplication is represented by the @ operator
M = np.array([ [1, 1],  [1, -1] ], dtype=complex) 
M @ np.array([[2], [3]], dtype=complex) 

array([[ 5.+0.j],
       [-1.+0.j]])

Listing 2.7. Timing NumPy evaluation for matrix multiplication 


In [ ]:
def matmul(A, B):
    n_rows_A = len(A)
    n_cols_A = len(A[0])
    n_rows_B = len(B)
    n_cols_B = len(B[0])
    assert n_cols_A == n_rows_B 
    '''The inner dimensions of both matrices need to agree in order for matrix multiplication to make sense. Thinking of each matrix as representing a linear function, the first index (the number of rows) tells us how large each output is, while the second index (the number of columns) tells us how large each input is. Thus we need the outputs from the first function to be applied (the one on the right) to be of the same size as the inputs to the second function. This line checks that condition. '''
    return[
        [
            sum(
                A[idx_row][idx_inner]*B[idx_inner][idx_col]
                for idx_inner in range(n_cols_A)
            )
            for idx_col in range(n_cols_B)
        ]
        for idx_row in range(n_rows_A)
    ]
import numpy as np
X = np.array([[0+0j, 1+0j], [1+0j, 0+0j]])
Z = np.array([[1+0j, 0+0j], [0+0j, -1+0j]])
matmul(X,Z)


[[np.complex128(0j), np.complex128(-1+0j)],
 [np.complex128(1+0j), np.complex128(0j)]]

In [15]:
X @ Z

array([[ 0.+0.j, -1.+0.j],
       [ 1.+0.j,  0.+0.j]])

In [11]:
%timeit matmul(X,Z)

4.54 μs ± 175 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [12]:
%timeit X @ Z

901 ns ± 11.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


Listing 2.8. Computing vector dot products with NumPy 


In [16]:
import numpy as np
v = np.array([[-2],[-3]])
south_east = np.array([[1], [-1]])
np.linalg.norm(south_east)

np.float64(1.4142135623730951)

In [18]:
w = np.array([[1],[-1]])/np.sqrt(2)
np.linalg.norm(w)

np.float64(0.9999999999999999)

In [19]:
v.transpose()

array([[-2, -3]])

In [20]:
v.transpose()@w

array([[0.70710678]])

Listing 2.9. Representing qubits in code with NumPy 


In [21]:
ket0 = np.array([[1],[0]])
ket0

array([[1],
       [0]])

In [22]:
ket1 = np.array([[0],[1]])
ket1

array([[0],
       [1]])

Listing 2.10. The vector representation of |+⟩


In [23]:
ket_plus = (ket0+ket1)/np.sqrt(2)
ket_plus

array([[0.70710678],
       [0.70710678]])

In [24]:
ket_minus = (ket0-ket1)/np.sqrt(2)
ket_minus

array([[ 0.70710678],
       [-0.70710678]])

Listing 2.11. Defining the Hadamard operation 


In [26]:
H = np.array([[1,1],[1,-1]])/np.sqrt(2)
H @ ket0

array([[0.70710678],
       [0.70710678]])

In [27]:
H@ ket1

array([[ 0.70710678],
       [-0.70710678]])

Listing 2.12. Representing the quantum NOT gate 


In [28]:
X = np.array([[0,1],[1,0]])
X @ ket0

array([[0],
       [1]])

In [ ]:
(X @ ket0 ==ket1).all()
# We can confirm that X transforms |0⟩ to |1⟩. The NumPy method all() returns True if every element of X @ ket0 == ket1 is True; that is, if every element of the array X @ ket0 is equal to the corresponding element of ket1.

np.True_

In [ ]:
X @ H@ ket0
#The X operation doesn’t do anything to H|0, since X will swap |0⟩ and |1⟩ and H|0 is already a sum of the two kets: (|0⟩ + |1⟩) / √2 = (|1⟩ + |0⟩) / √2. We can confirm this by using the @ operator again to multiply X by a Python value representing the state |+⟩ = H |0⟩ . We can express that value as H @ ket0.

array([[0.70710678],
       [0.70710678]])