Chapter 4. Nonlocal Games: Working with multiple qubits

In [2]:
import numpy as np 
ket0 = np.array([[1], [0]])
ket1 = np.array([[0], [1]]) 
np.kron(ket0, ket1) 

array([[0],
       [1],
       [0],
       [0]])

In [3]:
import numpy as np 
ket0 = np.array([[1], [0]]) 
from functools import reduce 
reduce(np.kron, [ket0] * 4) 

array([[1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [5]:
import numpy as np 
A = np.array([[1, 3], [5, 7]])
B = np.array([[2, 4], [6, 8]]) 
np.kron(A, B) 

array([[ 2,  4,  6, 12],
       [ 6,  8, 18, 24],
       [10, 20, 14, 28],
       [30, 40, 42, 56]])

In [32]:
import qutip as qt
from qutip.core.gates import hadamard_transform
import numpy as np
import matplotlib
qt.Qobj([[np.cos(0.2)], [np.sin(0.2)]])

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[0.98006658]
 [0.19866933]]

In [16]:
ket0 = qt.basis(2,0)
ket0

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [0.]]

In [22]:
ket1 = qt.basis(3,0)
ket1

Quantum object: dims=[[3], [1]], shape=(3, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [0.]
 [0.]]

In [23]:
qt.sigmax()

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=True
Qobj data =
[[0. 1.]
 [1. 0.]]

In [24]:
psi = qt.basis(2,0)
phi = qt.basis(2,1)
qt.tensor(psi, phi)

Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]]

In [37]:
H = hadamard_transform(N=2)
I = qt.qeye(2)
qt.tensor(H, I)

Quantum object: dims=[[2, 2, 2], [2, 2, 2]], shape=(8, 8), type='oper', dtype=Dia, isherm=True
Qobj data =
[[ 0.5  0.   0.5  0.   0.5  0.   0.5  0. ]
 [ 0.   0.5  0.   0.5  0.   0.5  0.   0.5]
 [ 0.5  0.  -0.5  0.   0.5  0.  -0.5  0. ]
 [ 0.   0.5  0.  -0.5  0.   0.5  0.  -0.5]
 [ 0.5  0.   0.5  0.  -0.5  0.  -0.5  0. ]
 [ 0.   0.5  0.   0.5  0.  -0.5  0.  -0.5]
 [ 0.5  0.  -0.5  0.  -0.5  0.   0.5  0. ]
 [ 0.   0.5  0.  -0.5  0.  -0.5  0.   0.5]]